In [1]:
import sklearn

print(sklearn.__version__)

1.3.0


In [19]:
from sklearn.datasets import load_iris

iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [16]:
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)
iris_df = pd.DataFrame(data=iris_data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, 
                                    test_size = 0.2, random_state = 11)
print(X_train[0])

[5.1 3.5 1.4 0.2]


In [ ]:
# 학습 / 예측
dt_clf = DecisionTreeClassifier(random_state = 11)
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)


In [20]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   label              150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [105]:
# 학습 : 머신러닝한테 공부 
# 예측 : 머신러닝 테스트 (공부잘했냐 안했냐 판단) 필수품 : 시험지
# 시험지 : 학습 / 테스트 데이터로 나눠서 테스트 데이터를 시험지로 선택

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label,
                                                    test_size = 0.2, 
                                                    random_state = 11)

In [102]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(120, 4) (30, 4) (120,) (30,)


In [133]:
train, test = train_test_split(iris_df,test_size = 0.2,random_state = 11)
# print(train.shape, test.shape)
train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
115                6.4               3.2                5.3               2.3   
116                6.5               3.0                5.5               1.8   
117                7.7               3.8                6.7               2.2   
118                7.7               2.6                6.9               2.3   
119                6.0               2.2                5.0               1.5   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
115      2  
116      2  
117      2  
118      2  
119      2  

[120 rows x 5 columns]

In [ ]:
# stratify : 종속변수의 범주를 균등하게 만들어줌
# test : 30 - 0,1,2   >>  0: 5, 1 : 10, 2 : 15  
# stratify >> 0 : 10, 1 : 10, 2 : 10

In [58]:
import numpy as np

np.random.seed(0)
np.random.randn(2,5)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ]])

In [ ]:
# x + y = 0
# x - y = 0
# x - 2y = 1

In [134]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
# 학습
dt_clf = DecisionTreeClassifier(random_state = 11)
# y = ax + b

dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [144]:
dt_clf.classes_

array([0, 1, 2])

In [145]:
# 예측
pred = dt_clf.predict(X_test)
# 학습을 통해서 a = 2, b = -3이라것을 확인했으면
# y = 2x - 3 
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [146]:
29/30

0.9666666666666667

In [147]:
# 평가
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, pred)
print('예측 정확도: {0:.4f}'.format(acc))

예측 정확도: 0.9333


In [153]:
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [149]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [158]:
(y_test.size - (y_test - pred).astype(bool).sum()) / y_test.size

0.9333333333333333

In [ ]:
# 머신러닝 - 학습 / 예측 / 평가
# 데이터 전처리

In [ ]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit()
model.predict()

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit()
sc.transform()

In [167]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [170]:
from sklearn.datasets import load_iris

data = load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [161]:
keys = iris_data.keys()
print(keys)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [178]:
from sklearn.datasets import load_iris

data = load_iris()

df = pd.DataFrame(data['data'], columns = data['feature_names'])
df['target'] = data['target']
df['target'] = df['target'].apply(lambda x : data['target_names'][x])
df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   target  
0  setosa  
1  setosa  
2  setosa

In [182]:
# df가 종속변수 + 독립변수 합쳐진 모양일 때 나누는 방법
# 1. 종속 / 독립 변수로 나눠서 train_test_split한다.
y_df = df['target']
x_df = df.drop('target', axis = 1)

X_train, X_test, y_train, y_test = train_test_split(x_df, y_df, test_size = 0.2,
                                                   random_state=0)

In [183]:
# 2. train_test_split을 먼저하고 종속 / 독립 변수로 나누기
train, test = train_test_split(df, test_size = 0.2, random_state=0)

y_train = train.loc['target']
x_train = train[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']]

y_test = test.iloc[:, -1]
x_test = test.iloc[:, :-1]

In [186]:
test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
114                5.8               2.8                5.1               2.4   
62                 6.0               2.2                4.0               1.0   
33                 5.5               4.2                1.4               0.2   
107                7.3               2.9                6.3               1.8   
7                  5.0               3.4                1.5               0.2   
100                6.3               3.3                6.0               2.5   
40                 5.0               3.5                1.3               0.3   
86                 6.7               3.1                4.7               1.5   
76                 6.8               2.8                4.8               1.4   
71                 6.1               2.8                4.0               1.3   
134                6.1               2.6                5.6               1.4   
51                 6.4               3.2                4.5               1.5   
73                 6.1               2.8                4.7               1.2   
54                 6.5               2.8                4.6               1.5   
63                 6.1               2.9                4.7               1.4   
37                 4.9               3.6                1.4               0.1   
78                 6.0               2.9                4.5               1.5   
90                 5.5               2.6                4.4               1.2   
45                 4.8               3.0                1.4               0.3   
16                 5.4               3.9                1.3               0.4   
121                5.6               2.8                4.9               2.0   
66                 5.6               3.0                4.5               1.5   
24                 4.8               3.4                1.9               0.2   
8                  4.4               2.9                1.4               0.2   
126                6.2               2.8                4.8               1.8   
22                 4.6               3.6                1.0               0.2   
44                 5.1               3.8                1.9               0.4   
97                 6.2               2.9                4.3               1.3   
93                 5.0               2.3                3.3               1.0   
26                 5.0               3.4                1.6               0.4   

         target  
114   virginica  
62   versicolor  
33       setosa  
107   virginica  
7        setosa  
100   virginica  
40       setosa  
86   versicolor  
76   versicolor  
71   versicolor  
134   virginica  
51   versicolor  
73   versicolor  
54   versicolor  
63   versicolor  
37       setosa  
78   versicolor  
90   versicolor  
45       setosa  
16       setosa  
121   virginica  
66   versicolor  
24       setosa  
8        setosa  
126   virginica  
22       setosa  
44       setosa  
97   versicolor  
93   versicolor  
26       setosa

In [185]:
x_train.head(1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
137                6.4               3.1                5.5               1.8