In [1]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
user_based = np.array([[5,1,4,4],
                       [1,1,4,4],
                       [4,2,4,4],
                       [1,4,4,2]])
result = cosine_similarity(user_based)
result

array([[1.        , 0.85571696, 0.983282  , 0.71235927],
       [0.85571696, 1.        , 0.90373784, 0.81763162],
       [0.983282  , 0.90373784, 1.        , 0.82072935],
       [0.71235927, 0.81763162, 0.82072935, 1.        ]])

In [2]:
import pandas as pd

pd.DataFrame(result, columns = ['김', '이', '박', '최'], index = ['김', '이', '박', '최'])

김         이         박         최
김  1.000000  0.855717  0.983282  0.712359
이  0.855717  1.000000  0.903738  0.817632
박  0.983282  0.903738  1.000000  0.820729
최  0.712359  0.817632  0.820729  1.000000

In [9]:
from sklearn.neighbors import NearestNeighbors
k = 2
knn = NearestNeighbors(n_neighbors= k)
knn.fit(user_based)
top_k_distances, top_k_users = knn.kneighbors(user_based)
print(top_k_distances)
print(top_k_users)


[[0.         4.24264069]
 [0.         3.31662479]
 [0.         3.31662479]
 [0.         4.12310563]]
[[0 2]
 [1 2]
 [2 1]
 [3 1]]


In [7]:
user_based = np.array([[5,1,4,4, 0],
                       [1,1,4,4, 3],
                       [4,2,4,4, 4],
                       [1,4,4,2, 1]])
result = cosine_similarity(user_based)
result

array([[1.        , 0.76091364, 0.85985517, 0.70292363],
       [0.76091364, 1.        , 0.9246584 , 0.79163311],
       [0.85985517, 0.9246584 , 1.        , 0.78688948],
       [0.70292363, 0.79163311, 0.78688948, 1.        ]])

In [13]:
# 유사도를 기반으로 김씨가 아직 측정하지 않은 점수를 예측

# 유사한사람(박씨)의 E제품의 점수 : R
# 김씨 박씨랑의 유사도 값 : S
# E제품의 평균 평점 : M
# 김씨의 다른 제품의 평균 평점 : M2

# (R  +  ((M - M2)* S)) / S
(4 + (((8/3) - 3.5) * (1 / 4.24264069))) 

3.8035814498037697

array([0.76091364, 0.85985517, 0.70292363])

In [15]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')
movies =pd.read_csv('data/ml/tmdb_5000_movies.csv')
print(movies.shape)
movies.head(2)


(4803, 20)


budget  ... vote_count
0  237000000  ...      11800
1  300000000  ...       4500

[2 rows x 20 columns]

In [16]:
movies_df = movies[['id','title', 'genres', 'vote_average', 
'vote_count', 'popularity', 'keywords', 'overview']]
movies_df.head()


id  ...                                           overview
0   19995  ...  In the 22nd century, a paraplegic Marine is di...
1     285  ...  Captain Barbossa, long believed to be dead, ha...
2  206647  ...  A cryptic message from Bond’s past sends him o...
3   49026  ...  Following the death of District Attorney Harve...
4   49529  ...  John Carter is a war-weary, former military ca...

[5 rows x 8 columns]

In [19]:
genres = movies_df['genres'].iloc[0]

In [24]:
genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [23]:
eval(genres)

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [26]:
from ast import literal_eval

literal_eval(genres)

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [27]:
print(eval('1 + 1'))

2


In [37]:
literal_eval('[1,2,3]')

[1, 2, 3]

In [40]:
movies_df['genres'].apply(literal_eval)

0       [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
1       [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2       [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
3       [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
4       [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
                              ...                        
4798    [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
4799    [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
4800    [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4801                                                   []
4802                  [{'id': 99, 'name': 'Documentary'}]
Name: genres, Length: 4803, dtype: object

In [41]:
from ast import literal_eval
movies_df['genres'] = movies_df['genres'].apply(literal_eval)
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)

In [44]:
movies_df['genres'] = movies_df['genres'].apply(lambda x : [ y['name'] for y in x])
movies_df['keywords'] = movies_df['keywords'].apply(lambda x : [ y['name'] for y in x])
movies_df[['genres', 'keywords']].head()

genres                                           keywords
0  [Action, Adventure, Fantasy, Science Fiction]  [culture clash, future, space war, space colon...
1                   [Adventure, Fantasy, Action]  [ocean, drug abuse, exotic island, east india ...
2                     [Action, Adventure, Crime]  [spy, based on novel, secret agent, sequel, mi...
3               [Action, Crime, Drama, Thriller]  [dc comics, crime fighter, terrorist, secret i...
4           [Action, Adventure, Science Fiction]  [based on novel, mars, medallion, space travel...

In [50]:
from sklearn.feature_extraction.text import CountVectorizer

movies_df['genres_literal'] = movies_df['genres'].apply(lambda x : (' ').join(x))
count_vect = CountVectorizer(ngram_range=(1,2))
genre_mat = count_vect.fit_transform(movies_df['genres_literal'])
print(genre_mat.shape)

(4803, 276)


In [53]:
movies_df.head(1)

id  ...                                   keywords_literal
0  19995  ...  culture clash future space war space colony so...

[1 rows x 10 columns]

In [54]:
test_df = movies_df[['vote_average','vote_count','popularity']]
test_df.head(1)

vote_average  vote_count  popularity
0           7.2       11800  150.437577

In [55]:
genres_df = pd.DataFrame(genre_mat.toarray(), columns = count_vect.get_feature_names_out())

In [56]:
pd.concat([test_df, genres_df], axis = 1)

vote_average  vote_count  ...  western romance  western thriller
0              7.2       11800  ...                0                 0
1              6.9        4500  ...                0                 0
2              6.3        4466  ...                0                 0
3              7.6        9106  ...                0                 0
4              6.1        2124  ...                0                 0
...            ...         ...  ...              ...               ...
4798           6.6         238  ...                0                 0
4799           5.9           5  ...                0                 0
4800           7.0           6  ...                0                 0
4801           5.7           7  ...                0                 0
4802           6.3          16  ...                0                 0

[4803 rows x 279 columns]

In [48]:
movies_df['keywords_literal'] = movies_df['keywords'].apply(lambda x : (' ').join(x))
count_vect = CountVectorizer(ngram_range=(1,2))
keywords_mat = count_vect.fit_transform(movies_df['keywords_literal'])
print(keywords_mat.shape)

(4803, 41554)


In [49]:
count_vect.get_feature_names_out()

array(['11', '11 2001', '11 helicopter', ..., '绝地奶霸', '绝地奶霸 卧底肥妈', '超级妈妈'],
      dtype=object)

In [57]:
from sklearn.metrics.pairwise import cosine_similarity
genre_sim = cosine_similarity(genre_mat, genre_mat)

print(genre_sim.shape)
print(genre_sim)

(4803, 4803)
[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]
 [0.59628479 1.         0.4        ... 0.         0.         0.        ]
 [0.4472136  0.4        1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]


In [58]:
genre_sim_sorted_ind = genre_sim.argsort()[:, ::-1]
print(genre_sim_sorted_ind)


[[   0 3494  813 ... 3038 3037 2401]
 [ 262    1  129 ... 3069 3067 2401]
 [   2 1740 1542 ... 3000 2999 2401]
 ...
 [4800 3809 1895 ... 2229 2230    0]
 [4802 1594 1596 ... 3204 3205    0]
 [4802 4710 4521 ... 3140 3141    0]]


In [59]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]
    similar_indexes = similar_indexes.reshape(-1)
    return df.iloc[similar_indexes]


In [60]:
similar_movies = find_sim_movie(movies_df, genre_sim_sorted_ind, 'The Godfather',10)
similar_movies


id  ...                                   keywords_literal
2731     240  ...  italo-american cuba vororte melancholy praise ...
1243     203  ...  epilepsy protection money secret love money re...
3636   36351  ...  suicide drug dealer redemption addict existent...
1946   11699  ...  police brutality organized crime policeman ill...
2640     400  ...  father son relationship bounty hunter boat way...
4065  364083  ...                          new york state hate crime
1847     769  ...  prison based on novel florida 1970s mass murde...
4217    9344  ...                                 puberty first time
883      640  ...  con man biography fbi agent overhead camera sh...
3866     598  ...  male nudity street gang brazilian photographer...

[10 rows x 10 columns]

In [66]:
movies_df[['title','vote_average','vote_count']].sort_values('vote_average', ascending=False)[:10]


title  vote_average  vote_count
3519          Stiff Upper Lips          10.0           1
4247     Me You and Five Bucks          10.0           2
4045     Dancer, Texas Pop. 81          10.0           1
4662            Little Big Top          10.0           1
3992                 Sardaarji           9.5           2
2386            One Man's Hero           9.3           2
2970        There Goes My Baby           8.5           2
1881  The Shawshank Redemption           8.5        8205
2796     The Prisoner of Zenda           8.4          11
3337             The Godfather           8.4        5893

In [67]:
C = movies_df['vote_average'].mean()
m = movies_df['vote_count'].quantile(0.5)
print('C:',round(C,3), ', m:',round(m,3))

C: 6.092 , m: 235.0


In [68]:
percentile = 0.6
m = movies_df['vote_count'].quantile(percentile)
C = movies_df['vote_average'].mean()
def weighted_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']
    return ( (v/(v+m)) * R ) + ( (m/(m+v)) * C ) 

movies_df['weighted_vote'] = movies_df.apply(weighted_vote_average, axis=1)

In [70]:
movies_df[['title','vote_average','weighted_vote']].sort_values('weighted_vote', ascending = False)[:10]

title  vote_average  weighted_vote
1881  The Shawshank Redemption           8.5       8.396052
3337             The Godfather           8.4       8.263591
662                 Fight Club           8.3       8.216455
3232              Pulp Fiction           8.3       8.207102
65             The Dark Knight           8.2       8.136930
1818          Schindler's List           8.3       8.126069
3865                  Whiplash           8.3       8.123248
809               Forrest Gump           8.2       8.105954
2294             Spirited Away           8.3       8.105867
2731    The Godfather: Part II           8.3       8.079586

In [71]:
movies_df[['title','vote_average','weighted_vote']].sort_values('vote_average', ascending=False)[:10]


title  vote_average  weighted_vote
3519          Stiff Upper Lips          10.0       6.102699
4247     Me You and Five Bucks          10.0       6.113170
4045     Dancer, Texas Pop. 81          10.0       6.102699
4662            Little Big Top          10.0       6.102699
3992                 Sardaarji           9.5       6.110483
2386            One Man's Hero           9.3       6.109409
2970        There Goes My Baby           8.5       6.105110
1881  The Shawshank Redemption           8.5       8.396052
2796     The Prisoner of Zenda           8.4       6.158767
3337             The Godfather           8.4       8.263591

In [73]:
import pandas as pd
import numpy as np
movies = pd.read_csv('data/ml/movies.csv')
ratings = pd.read_csv('data/ml/ratings.csv')
print(movies.shape)
print(ratings.shape)

(9742, 3)
(100836, 4)


In [74]:
movies

movieId  ...                                       genres
0           1  ...  Adventure|Animation|Children|Comedy|Fantasy
1           2  ...                   Adventure|Children|Fantasy
2           3  ...                               Comedy|Romance
3           4  ...                         Comedy|Drama|Romance
4           5  ...                                       Comedy
...       ...  ...                                          ...
9737   193581  ...              Action|Animation|Comedy|Fantasy
9738   193583  ...                     Animation|Comedy|Fantasy
9739   193585  ...                                        Drama
9740   193587  ...                             Action|Animation
9741   193609  ...                                       Comedy

[9742 rows x 3 columns]

In [75]:
ratings

userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [78]:
ratings = ratings[['userId', 'movieId', 'rating']]
ratings_matrix = ratings.pivot_table(values = 'rating', 
                                     index='userId', 
                                     columns='movieId')
ratings_matrix.head()


movieId  1       2       3       ...  193585  193587  193609
userId                           ...                        
1           4.0     NaN     4.0  ...     NaN     NaN     NaN
2           NaN     NaN     NaN  ...     NaN     NaN     NaN
3           NaN     NaN     NaN  ...     NaN     NaN     NaN
4           NaN     NaN     NaN  ...     NaN     NaN     NaN
5           4.0     NaN     NaN  ...     NaN     NaN     NaN

[5 rows x 9724 columns]

In [81]:
rating_movies = ratings.merge(movies, on='movieId')

In [82]:
ratings_matrix = rating_movies.pivot_table('rating', index='userId', columns='title')
ratings_matrix = ratings_matrix.fillna(0)
ratings_matrix.head(3)


title   '71 (2014)  ...  À nous la liberté (Freedom for Us) (1931)
userId              ...                                           
1              0.0  ...                                        0.0
2              0.0  ...                                        0.0
3              0.0  ...                                        0.0

[3 rows x 9719 columns]

In [84]:
ratings_matrix.shape

(610, 9719)

In [88]:
ratings_matrix_T = ratings_matrix.transpose()
item_sim = cosine_similarity(ratings_matrix_T)
item_sim_df = pd.DataFrame(data=item_sim, 
                            index=ratings_matrix.columns,
                            columns=ratings_matrix.columns)


In [89]:
print(item_sim_df.shape)
item_sim_df.head()

(9719, 9719)


title                                    '71 (2014)  ...  À nous la liberté (Freedom for Us) (1931)
title                                                ...                                           
'71 (2014)                                      1.0  ...                                        0.0
'Hellboy': The Seeds of Creation (2004)         0.0  ...                                        0.0
'Round Midnight (1986)                          0.0  ...                                        0.0
'Salem's Lot (2004)                             0.0  ...                                        0.0
'Til There Was You (1997)                       0.0  ...                                        0.0

[5 rows x 9719 columns]

In [90]:
item_sim_df["Godfather, The (1972)"].sort_values(ascending=False)[:6]

title
Godfather, The (1972)                        1.000000
Godfather: Part II, The (1974)               0.821773
Goodfellas (1990)                            0.664841
One Flew Over the Cuckoo's Nest (1975)       0.620536
Star Wars: Episode IV - A New Hope (1977)    0.595317
Fargo (1996)                                 0.588614
Name: Godfather, The (1972), dtype: float64

In [91]:
# 개인 예측 평점 함수
def predict_rating(ratings_arr, item_sim_arr ):
    ratings_pred = ratings_arr.dot(item_sim_arr)/ np.array([np.abs(item_sim_arr).sum(axis=1)])
    return ratings_pred

ratings_pred = predict_rating(ratings_matrix.values , item_sim_df.values)


In [93]:
ratings_pred_matrix = pd.DataFrame(data=ratings_pred, 
                                    index= ratings_matrix.index,
                                    columns = ratings_matrix.columns)
ratings_pred_matrix.head(3)

title   '71 (2014)  ...  À nous la liberté (Freedom for Us) (1931)
userId              ...                                           
1         0.070345  ...                                   0.720347
2         0.018260  ...                                   0.000000
3         0.011884  ...                                   0.084501

[3 rows x 9719 columns]

In [114]:
actual =ratings_matrix.values[ratings_matrix.values.nonzero()].flatten()

In [115]:
pred = ratings_pred[ratings_matrix.values.nonzero()].flatten()

In [116]:
from sklearn.metrics import mean_squared_error

mean_squared_error(actual, pred)

9.895354759094706

In [121]:
from sklearn.metrics import mean_squared_error
def get_rmse(pred, actual):
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return np.sqrt(mean_squared_error(pred, actual))

print('아이템 기반 모든 인접 이웃 RMSE: ', get_rmse(ratings_pred, ratings_matrix.values ))


아이템 기반 모든 인접 이웃 RMSE:  3.1456882806620725


In [122]:
def predict_rating_topsim(ratings_arr, item_sim_arr, n=20):
    # 유저-아이템 행렬만큼 0행렬 생성
    pred = np.zeros(ratings_arr.shape)
    # 아이템 개수 만큼 수행
    for col in range(ratings_arr.shape[1]):
        top_n_items = [np.argsort(item_sim_arr[:, col])[:-n-1:-1]]
        # 모든 유저에 대한
        for row in range(ratings_arr.shape[0]):
            pred[row, col] = item_sim_arr[col, :][top_n_items].dot(ratings_arr[row, :][top_n_items].T) 
            pred[row, col] /= np.sum(np.abs(item_sim_arr[col, :][top_n_items])) 
    return pred


In [125]:
ratings_pred = predict_rating_topsim(ratings_matrix.values , item_sim_df.values, n=20)

In [126]:
ratings_pred

array([[0.        , 0.        , 0.        , ..., 0.        , 1.67729077,
        0.28437161],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.17548935, 0.70242952,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [3.7       , 0.11494779, 0.        , ..., 0.74587428, 0.17047454,
        0.        ]])

In [130]:
print('아이템 기반 인접 TOP-20 이웃 RMSE: ', get_rmse(ratings_pred, ratings_matrix.values ))

아이템 기반 인접 TOP-20 이웃 RMSE:  1.9222407204687304


In [168]:
ratings_matrix.iloc[2].sort_values(ascending=False).head(40)

title
Saturn 3 (1980)                                                             5.0
Hangar 18 (1980)                                                            5.0
The Lair of the White Worm (1988)                                           5.0
Escape from L.A. (1996)                                                     5.0
Android (1982)                                                              5.0
Road Warrior, The (Mad Max 2) (1981)                                        5.0
Troll 2 (1990)                                                              5.0
Galaxy of Terror (Quest) (1981)                                             5.0
Alien Contamination (1980)                                                  5.0
Death Race 2000 (1975)                                                      5.0
Piranha (1978)                                                              4.5
Conan the Barbarian (1982)                                                  4.5
Looker (1981)                     

In [170]:
ratings_pred_matrix = pd.DataFrame(data=ratings_pred, 
index= ratings_matrix.index,
columns = ratings_matrix.columns)
ratings_pred_matrix

title   '71 (2014)  ...  À nous la liberté (Freedom for Us) (1931)
userId              ...                                           
1              0.0  ...                                   0.284372
2              0.0  ...                                   0.000000
3              0.0  ...                                   0.000000
4              0.0  ...                                   0.000000
5              0.0  ...                                   0.000000
...            ...  ...                                        ...
606            0.0  ...                                   0.189602
607            0.0  ...                                   0.000000
608            0.0  ...                                   0.000000
609            0.0  ...                                   0.000000
610            3.7  ...                                   0.000000

[610 rows x 9719 columns]

In [171]:
user_rating_id = ratings_matrix.loc[9, :]
user_rating_id[ user_rating_id > 0].sort_values(ascending=False)[:10]

title
Adaptation (2002)                                                                 5.0
Citizen Kane (1941)                                                               5.0
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    5.0
Producers, The (1968)                                                             5.0
Lord of the Rings: The Two Towers, The (2002)                                     5.0
Lord of the Rings: The Fellowship of the Ring, The (2001)                         5.0
Back to the Future (1985)                                                         5.0
Austin Powers in Goldmember (2002)                                                5.0
Minority Report (2002)                                                            4.0
Witness (1985)                                                                    4.0
Name: 9, dtype: float64

In [172]:
def get_unseen_movies(ratings_matrix, userId):
    user_rating = ratings_matrix.loc[userId,:]
    already_seen = user_rating[ user_rating > 0].index.tolist()
    movies_list = ratings_matrix.columns.tolist()
    unseen_list = [ movie for movie in movies_list if movie not in already_seen]
    return unseen_list


In [173]:
def recomm_movie_by_userid(pred_df, userId, unseen_list, top_n=10):
    recomm_movies = pred_df.loc[userId, unseen_list].sort_values(ascending=False)[:top_n]
    return recomm_movies

In [191]:
unseen_list = get_unseen_movies(ratings_matrix, 9)
recomm_movies = recomm_movie_by_userid(ratings_pred_matrix, 9, 
                                        unseen_list, top_n=10)
recomm_movies = pd.DataFrame(data=recomm_movies.values,
                            index=recomm_movies.index,
                            columns=['pred_score'])
recomm_movies


pred_score
title                                                         
Rear Window (1954)                                    5.633395
South Park: Bigger, Longer and Uncut (1999)           5.436370
Blade Runner (1982)                                   5.394966
Gattaca (1997)                                        5.144675
Roger & Me (1989)                                     5.130188
Rounders (1998)                                       5.074881
Ben-Hur (1959)                                        5.037542
Yojimbo (1961)                                        5.033375
Indiana Jones and the Last Crusade (1989)             5.028594
Star Wars: Episode V - The Empire Strikes Back ...    5.011059

In [179]:
ratings_matrix['Godfather: Part II, The (1974)']

userId
1      0.0
2      0.0
3      0.0
4      0.0
5      0.0
      ... 
606    4.0
607    0.0
608    4.5
609    0.0
610    5.0
Name: Godfather: Part II, The (1974), Length: 610, dtype: float64

In [183]:
def get_rmse(R, P, Q, non_zeros):
    error = 0
    # 두개의 분해된 행렬 P와 Q.T의 내적 곱으로 예측 R 행렬 생성
    full_pred_matrix = np.dot(P, Q.T)
    # 실제 R 행렬에서 널이 아닌 값의 위치 인덱스 추출하여 실제 R 행렬과 예측 행렬의 RMSE 추출
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)
    return rmse


In [186]:
def matrix_factorization(R, K, steps=100, learning_rate=0.01, r_lambda = 0.01):
    # 만약 데이터프레임이 들어오면
    if type(R) == 'pandas.core.frame.DataFrame':
        R = R.values

    num_users, num_items = R.shape
    # P와 Q 매트릭스의 크기를 지정하고 정규분포를 가진 랜덤한 값으로 입력합니다. 
    np.random.seed(1)
    P = np.random.normal(scale=1./ K, size=(num_users, K))
    Q = np.random.normal(scale=1./ K, size=(num_items, K))
    break_count = 0
    # R > 0 인 행 위치, 열 위치, 값을 non_zeros 리스트 객체에 저장. 
    non_zeros = [ (i, j, R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j] > 0 ]
    # 이전 코드에 이어서 작성
    # SGD기법으로 P와 Q 매트릭스를 계속 업데이트. 
    for step in range(steps):
        for i, j, r in non_zeros:
            # 실제 값과 예측 값의 차이인 오류 값 구함
            eij = r - np.dot(P[i, :], Q[j, :].T)
            # Regularization을 반영한 SGD 업데이트 공식 적용
            P[i,:] = P[i,:] + learning_rate*(eij * Q[j, :] - r_lambda*P[i,:])
            Q[j,:] = Q[j,:] + learning_rate*(eij * P[i, :] - r_lambda*Q[j,:])
        
        
        if (step % 10) == 0 :
            rmse = get_rmse(R, P, Q, non_zeros)
            print("### iteration step : ", step," rmse : ", rmse)
    return P, Q


In [187]:
P, Q = matrix_factorization(ratings_matrix.values, K=50, steps=100, 
                            learning_rate=0.01, r_lambda = 0.01)
pred_matrix = np.dot(P, Q.T)


### iteration step :  0  rmse :  2.9023619751336867
### iteration step :  10  rmse :  0.7335768591017927
### iteration step :  20  rmse :  0.5115539026853442
### iteration step :  30  rmse :  0.37261628282537446
### iteration step :  40  rmse :  0.2960818299181014
### iteration step :  50  rmse :  0.2520353192341642
### iteration step :  60  rmse :  0.22487503275269854
### iteration step :  70  rmse :  0.20685455302331537
### iteration step :  80  rmse :  0.19413418783028685
### iteration step :  90  rmse :  0.18470082002720403


In [189]:
ratings_pred_matrix = pd.DataFrame(data=pred_matrix, index= ratings_matrix.index,
columns = ratings_matrix.columns)
ratings_pred_matrix.head(3)


title   '71 (2014)  ...  À nous la liberté (Freedom for Us) (1931)
userId              ...                                           
1         3.140208  ...                                   0.881563
2         3.160184  ...                                   0.773066
3         2.399852  ...                                   0.459202

[3 rows x 9719 columns]

In [190]:
# 사용자가 관람하지 않는 영화명 추출
unseen_list = get_unseen_movies(ratings_matrix, 9)
# 아이템 기반의 인접 이웃 협업 필터링으로 영화 추천
recomm_movies = recomm_movie_by_userid(ratings_pred_matrix, 9, 
unseen_list, top_n=10)
# 평점 데이타를 DataFrame으로 생성. 
recomm_movies = pd.DataFrame(data=recomm_movies.values,
index=recomm_movies.index, columns=['pred_score'])
recomm_movies


pred_score
title                                                         
Rear Window (1954)                                    5.633395
South Park: Bigger, Longer and Uncut (1999)           5.436370
Blade Runner (1982)                                   5.394966
Gattaca (1997)                                        5.144675
Roger & Me (1989)                                     5.130188
Rounders (1998)                                       5.074881
Ben-Hur (1959)                                        5.037542
Yojimbo (1961)                                        5.033375
Indiana Jones and the Last Crusade (1989)             5.028594
Star Wars: Episode V - The Empire Strikes Back ...    5.011059

In [192]:
joke = pd.read_csv('data/ml/JokeText.csv')
joke

JokeId                                           JokeText
0        0  A man visits the doctor. The doctor says "I ha...
1        1  This couple had an excellent relationship goin...
2        2  Q. What's 200 feet long and has 4 teeth? \n\nA...
3        3  Q. What's the difference between a man and a t...
4        4  Q.\tWhat's O. J. Simpson's Internet address? \...
..     ...                                                ...
95      95  Two attorneys went into a diner and ordered tw...
96      96  A teacher is explaining to her class how diffe...
97      97  Age and Womanhood\n\n1. Between the ages of 13...
98      98  A bus station is where a bus stops.\nA train s...
99      99  Q: Whats the difference between greeting a Que...

[100 rows x 2 columns]

In [194]:
# 컨텐츠 기반 추천 시스템
# 스탑워드 제거
from nltk.corpus import stopwords

stop_words = stopwords.words('english')


from sklearn.feature_extraction.text import CountVectorizer

cnt_vect = CountVectorizer(stop_words=stop_words, ngram_range=(1,2))

In [195]:
data = cnt_vect.fit_transform(joke['JokeText'])

In [201]:
from sklearn.metrics.pairwise import cosine_similarity

data_similarity = cosine_similarity(data)
data_sim_sorted_index = np.argsort(data_similarity, axis = 1)[:, ::-1]

In [211]:
print(joke['JokeText'].iloc[4])

sim_top1 = data_sim_sorted_index[4, 1]
print(joke['JokeText'].iloc[sim_top1], data_similarity[4, 1])

Q.	What's O. J. Simpson's Internet address? 
A.	Slash, slash, backslash, slash, slash, escape.

Q: Whats the difference between greeting a Queen and greeting the
President of the United  States?

A: You only have to get on one knee to greet the queen.
 0.0


In [215]:
df = pd.read_csv('data/ml/UserRatings1.csv')
df2 = pd.read_csv('data/ml/UserRatings2.csv')

In [232]:
ratings = pd.concat([df, df2], axis = 1)

In [235]:
ratings.drop('JokeId', axis = 1, inplace=True)

In [236]:
ratings.head(1)

User1  User2  User3  ...  User73419  User73420  User73421
0    5.1  -8.79   -3.5  ...        NaN        NaN        NaN

[1 rows x 73421 columns]

In [237]:
ratings = ratings.fillna(0)

In [238]:
item_sim = cosine_similarity(ratings)

In [239]:
item_sim

array([[1.        , 0.37925488, 0.37498919, ..., 0.14830552, 0.12790649,
        0.19582158],
       [0.37925488, 1.        , 0.29501574, ..., 0.20407971, 0.11235442,
        0.2303598 ],
       [0.37498919, 0.29501574, 1.        , ..., 0.15467265, 0.144623  ,
        0.24501581],
       ...,
       [0.14830552, 0.20407971, 0.15467265, ..., 1.        , 0.26851849,
        0.40310982],
       [0.12790649, 0.11235442, 0.144623  , ..., 0.26851849, 1.        ,
        0.29480081],
       [0.19582158, 0.2303598 , 0.24501581, ..., 0.40310982, 0.29480081,
        1.        ]])

In [240]:
predict_rating(ratings.T.values, item_sim)

array([[ 1.8788631 ,  1.64383813,  1.66106134, ...,  2.23637422,
         2.01582286,  2.40971891],
       [-1.13559497, -0.83240885, -0.96422406, ...,  0.05167617,
        -0.84048637, -0.09169268],
       [-0.89556628, -0.9544732 , -0.9231974 , ..., -0.53411101,
        -0.83777306, -0.41691658],
       ...,
       [-0.11283114, -0.17175863, -0.18011596, ..., -0.0653649 ,
        -0.09629644, -0.09319897],
       [-0.26547756, -0.32562563, -0.34479273, ..., -0.27059605,
        -0.36188635, -0.29254442],
       [ 0.21866213,  0.25330071,  0.25249808, ...,  0.2469522 ,
         0.23034856,  0.23151465]])

In [241]:
def predict_rating_topsim(ratings_arr, item_sim_arr, n=20):
    # 유저-아이템 행렬만큼 0행렬 생성
    pred = np.zeros(ratings_arr.shape)
    # 아이템 개수 만큼 수행
    for col in range(ratings_arr.shape[1]):
        top_n_items = [np.argsort(item_sim_arr[:, col])[:-n-1:-1]]
        # 모든 유저에 대한
        for row in range(ratings_arr.shape[0]):
            pred[row, col] = item_sim_arr[col, :][top_n_items].dot(ratings_arr[row, :][top_n_items].T) 
            pred[row, col] /= np.sum(np.abs(item_sim_arr[col, :][top_n_items])) 
    return pred

ratings_pred = predict_rating_topsim(ratings.T.values, item_sim, n=10)

array([[ 1.99357847,  1.26303532,  2.46996576, ...,  2.78634753,
         3.840922  ,  4.45461084],
       [-5.16163695, -2.63194021, -1.12803361, ...,  2.042618  ,
        -0.49213216,  1.27724343],
       [-1.91229106, -2.19317516, -1.36338196, ..., -0.85575986,
        -1.03873851,  0.72119866],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.12265162,
         0.        ,  0.13355089],
       [ 0.        , -0.56140815, -0.5363536 , ...,  0.        ,
        -0.72122919, -0.56239593],
       [ 0.        ,  0.        ,  0.63823804, ...,  0.        ,
         0.        ,  0.        ]])

In [245]:
ratings.T

0     1     2     3   ...    96    97    98    99
User1      5.10  4.90  1.75 -4.17  ... -4.95 -0.19  3.25  4.37
User2     -8.79 -0.87  1.99 -4.61  ... -0.97  4.13 -1.84  2.96
User3     -3.50 -2.91 -2.18 -0.10  ... -6.46 -6.89 -2.33 -7.38
User4      7.14 -3.88 -3.06  0.05  ... -2.57  1.07  2.33 -0.34
User5     -8.79 -0.58 -0.58  8.98  ...  9.17  9.17  9.08  8.98
...         ...   ...   ...   ...  ...   ...   ...   ...   ...
User73417  0.00  0.00  0.00  0.00  ...  0.78  0.00  0.00  0.00
User73418  0.00  0.00  0.00  0.00  ...  0.00  0.00  0.00  0.00
User73419  0.00  0.00  0.00  0.00  ...  0.00  0.00  0.00  0.00
User73420  0.00  0.00  0.00  0.00  ...  0.00  0.00  0.00  0.00
User73421  0.00  0.00  0.00  0.00  ...  0.00  0.00  0.00  0.00

[73421 rows x 100 columns]

In [249]:
ratings.T.values.shape

(73421, 100)

In [253]:
P, Q = matrix_factorization(ratings.T.values[:1000], K=50, steps=100, 
                            learning_rate=0.01, r_lambda = 0.01)
pred_matrix = np.dot(P, Q.T)

### iteration step :  0  rmse :  3.6470913534047957
### iteration step :  10  rmse :  1.3631954202763674
### iteration step :  20  rmse :  1.090384191598709
### iteration step :  30  rmse :  0.9392707051072977
### iteration step :  40  rmse :  0.8231197333374142
### iteration step :  50  rmse :  0.7636202003108639
### iteration step :  60  rmse :  0.7332630124607213
### iteration step :  70  rmse :  0.7155392941801422
### iteration step :  80  rmse :  0.7042025792941505
### iteration step :  90  rmse :  0.6963687909612455


In [254]:
def re_matrix_factorization(R, K, P, Q, steps=100, learning_rate=0.01, r_lambda = 0.01):
    # 만약 데이터프레임이 들어오면
    if type(R) == 'pandas.core.frame.DataFrame':
        R = R.values

    num_users, num_items = R.shape
    # P와 Q 매트릭스의 크기를 지정하고 정규분포를 가진 랜덤한 값으로 입력합니다. 
    np.random.seed(1)
    
    break_count = 0
    # R > 0 인 행 위치, 열 위치, 값을 non_zeros 리스트 객체에 저장. 
    non_zeros = [ (i, j, R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j] > 0 ]
    # 이전 코드에 이어서 작성
    # SGD기법으로 P와 Q 매트릭스를 계속 업데이트. 
    for step in range(steps):
        for i, j, r in non_zeros:
            # 실제 값과 예측 값의 차이인 오류 값 구함
            eij = r - np.dot(P[i, :], Q[j, :].T)
            # Regularization을 반영한 SGD 업데이트 공식 적용
            P[i,:] = P[i,:] + learning_rate*(eij * Q[j, :] - r_lambda*P[i,:])
            Q[j,:] = Q[j,:] + learning_rate*(eij * P[i, :] - r_lambda*Q[j,:])
        
        
        if (step % 10) == 0 :
            rmse = get_rmse(R, P, Q, non_zeros)
            print("### iteration step : ", step," rmse : ", rmse)
    return P, Q


In [255]:
P, Q = re_matrix_factorization(ratings.T.values[:1000], K=50, P = P, Q =  Q,
                               steps=100, learning_rate=0.01, r_lambda = 0.01)
pred_matrix = np.dot(P, Q.T)

### iteration step :  0  rmse :  0.6905976923056361
### iteration step :  10  rmse :  0.686128752462404
### iteration step :  20  rmse :  0.6825320804651892
### iteration step :  30  rmse :  0.6795470198248237
### iteration step :  40  rmse :  0.6770063034614486
### iteration step :  50  rmse :  0.6747985806390568
### iteration step :  60  rmse :  0.6728481561015756
### iteration step :  70  rmse :  0.6711028187228787
### iteration step :  80  rmse :  0.6695259114739507
### iteration step :  90  rmse :  0.6680909783971485


In [259]:
ratings_pred_matrix = pd.DataFrame(data=pred_matrix, index= ratings.T.iloc[:1000].index)
ratings_pred_matrix.head(5)

0         1         2   ...        97        98        99
User1  4.733444  4.993425  1.939537  ...  6.676542  2.802581  4.403072
User2  3.520674  3.337486  2.357588  ...  4.052778  2.076874  2.959704
User3  5.178465 -2.269292  0.400496  ...  4.786154  8.066287  8.887942
User4  7.690391  0.999467  1.678742  ...  1.543849  1.770051 -3.676911
User5 -0.064002  5.745111  8.738106  ...  9.026352  8.631170  9.468705

[5 rows x 100 columns]

In [260]:
ratings.T.head(5)

0     1     2     3     4   ...    95    96    97    98    99
User1  5.10  4.90  1.75 -4.17  5.15  ...  6.31 -4.95 -0.19  3.25  4.37
User2 -8.79 -0.87  1.99 -4.61  5.39  ... -1.02 -0.97  4.13 -1.84  2.96
User3 -3.50 -2.91 -2.18 -0.10  7.52  ...  3.98 -6.46 -6.89 -2.33 -7.38
User4  7.14 -3.88 -3.06  0.05  6.26  ...  3.93 -2.57  1.07  2.33 -0.34
User5 -8.79 -0.58 -0.58  8.98  7.67  ...  9.13  9.17  9.17  9.08  8.98

[5 rows x 100 columns]

In [261]:
# 사용자가 관람하지 않는 영화명 추출
unseen_list = get_unseen_movies(ratings.T.iloc[:1000], 'User1')
# 아이템 기반의 인접 이웃 협업 필터링으로 영화 추천
recomm_movies = recomm_movie_by_userid(ratings_pred_matrix, 'User1', 
                                        unseen_list, top_n=10)
# 평점 데이타를 DataFrame으로 생성. 
recomm_movies = pd.DataFrame(data=recomm_movies.values,
index=recomm_movies.index, columns=['pred_score'])
recomm_movies


pred_score
74   10.270013
9     8.493377
8     7.552769
97    6.676542
12    6.020305
30    5.924154
14    5.923867
18    5.858658
13    5.722287
3     5.534517