In [ ]:
import numpy as np

In [ ]:
#문제 1
# a=np.arange(1,26).reshape(5,5)   #dtype=np.int8 ?
a=np.arange(1,26, dtype=np.int8).reshape(5,5)

In [ ]:
np.savetxt('./data.csv',a,delimiter=',')

In [ ]:
#문제2
arr1=np.loadtxt('data.csv', dtype=str)
arr1

In [ ]:
## 지역별 전기요금
# 1) 데이터 불러오기
data=np.loadtxt('data/ex1_지역별전기요금.csv',delimiter=',',dtype=np.int_)  # dtype=np.int -error
data[:5,:] 

In [ ]:
# 2) 데이터 확인하기
print(data.shape)  
print(np.unique(data[:,0]))   # 중복값 제거
print(len(np.unique(data[:,0])))  # 중복값 제거위해 길이 비교

In [ ]:
# 데이터 확인(데이터 크기순 정렬) - argsort로 확인
# .sort로는 데이터 섞임
print(data[:,1].argsort())
print(data[data[:,1].argsort()])

In [ ]:
sorted_data=data[:,2].argsort()
data[sorted_data]        # 팬시 인덱스  

In [ ]:
# 내림차순 정렬로 바꾸기--> [::-1]] 붙이기
data[sorted_data][::-1]

In [ ]:
# 3) 데이터 통계
#전국대상 가구수의 합
print(np.sum(data[:,1]))

In [ ]:
#전력사용량 평균
print(data[:,2].mean())
print(round(data[:,2].mean(),2)) 

In [ ]:
np.sum(data, axis=0))   # 전체 colume별 합

In [ ]:
#가구당 평균전력 사용량이 평균이상인 지역과 대상 가구수
a=data[:,2].mean() # 가구당 평균 전력사용량의 전국평균
print(a)
print(data[data[:,2] > a, 0:2])

In [ ]:
#가구당 평균 전력 사용량이 평균 이상인 지역과 대상 가구수 추출
avg_ = data[:, 2].mean () # 가구당 평균 전력 사용량의 전국 평균
print(data[data[:, 2] >= avg_, 0:2])

In [ ]:
# 참고(불리언 인덱스)
data[:,2] > avg_ 

In [ ]:
##교통사망사고 데이터
#문제1 상위 3개(발생년도,건수,구성비) 데이터 추출
data=np.loadtxt('data/ex2_전년대비_시도별_교통사망사고.csv',delimiter=',',dtype=np.float_)  #np.float   -->error
data[:3,[0,2,3]]

In [ ]:

a=np.loadtxt('data/ex2_전년대비_시도별_교통사망사고.csv', delimiter=',', dtype=np.float_)
b=a[:3,[0,2,3]]
print(b)


In [ ]:
# 데이터 검사
data.shape

In [ ]:
#문제2) 세종에서 발생건수
ㅁprint(data[data[:,1]==10])

In [ ]:
print(data[data[:,1]==10])

In [ ]:
# 문제3) 전국 사고발생건수의 합계, 평균
print(np.sum(data[:, 2])) # 발생건수의 총합
data[:,2].mean()
print(round(np.sum(data[:, 2]) / 17, 2)) 

In [ ]:
np.sum(a[:,2])
print(round(np.sum(a[:,2])/17,2))

In [ ]:
# 문제4 교통사고 증감수가 가장 큰 지역의 모든 상황 출력
# 증감수 컬럼에서 가장 큰 값
print(np.max(data[:,4]))
print(data[np.argmax(data[:,4])]) # 증감수가 가장 큰 지역

In [ ]:
# 방법1 max
max_=(data[:,4]).max()
data[data[:,4] == max_]

In [ ]:
# 방법2  argmax
data[np.argmax(data[:,4])]
data[(data[:,4]).argmax()]

In [141]:
# 방법3  arqsort() 내림차순 sort해서 맨 위에것 가져오기
data[(data[:,4]).argsort() [::-1] ][0]   ## 잘 안씀

array([2014. ,    6. ,  182. ,    4. ,   19. ,   11.7])

In [ ]:
# 문제5) 사고 증감률이 가장 작은 지역의 모든 현황 출력
# 증감률 컬럼에서 가장 작은 값
print(np.min(data[:,5]))
print(data[np.argmin(data[:,5])]) # 증감률이 가장 작은 지역

In [143]:
np.argmin(a[:,5])
print(data[:,5].argmin())
print(a[np.argmin(a[:,5])])

7
[2014.     8.   163.     3.6  -47.   -22.4]


In [146]:
min_=(data[:,5]).min()
data[data[:,5] == min_]

array([[2014. ,    8. ,  163. ,    3.6,  -47. ,  -22.4]])

In [147]:
data[(data[:,5]).argsort()][0]

array([2014. ,    8. ,  163. ,    3.6,  -47. ,  -22.4])

In [ ]:
# 문제6) 건수 400건 이상인 곳의 지역과 발생건수, 증감수,증감률  =>bool 인덱스
# 사고 발생건수가 400건 이상인 데이터 추출
data[data[:,2] >= 400,:]  # data[data[:,2] >= 400]  같은 결과 나옴
data2 = data[data[:,2] >= 400,:]
print(data2[:, [1, 2, 4, 5]])


In [149]:
data[data[:,2] >= 400][:, [1,2,4,5]]  


array([[  2. , 872. , -45. ,  -4.9],
       [  3. , 401. , -45. , -10.1],
       [  4. , 464. , -41. ,  -8.1],
       [ 13. , 400. , -35. ,  -8. ]])