### Numpy  활용(함수, 연산 등)

In [ ]:
import numpy as np

In [ ]:
# shape 변환 --> reshape()
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2x3 형태의 2차원 배열
print(arr.reshape(3,2))

In [ ]:
tensor=np.array(range(1,37))
tensor.reshape(-1,3,4)

In [ ]:
tensor.reshape(-1,9)

In [ ]:
# 1차원 배열으로 만드는 flatten()
print(tensor.flatten())

In [ ]:
# list의 range와 같은 역할 --> arange
print(np.arange(0, 2, 0.2))

In [ ]:
print(np.arange(10, 0, -2))

In [ ]:
print(np.arange (0, 6, 0.2).reshape(3, 2,5))

In [ ]:
np.arange (0, 6, 0.2).size

In [ ]:
print(np.arange (100,191,10).reshape(2,5))

In [ ]:
print(np.arange(-2,2.1,0.5).reshape(3,3))

In [ ]:
np.arange(-2,2.1,0.5).size

In [ ]:
score =np.array ([[78, 91, 84, 89, 93, 65],[82, 87, 96, 79, 91, 73]])
print(score)

In [ ]:
# zeros
print(np.zeros((2,3)))

In [ ]:
# ones
print(np.ones(shape=(9, ), dtype=np.int8))

In [ ]:
# empty
print(np.empty(shape = (10,), dtype = np.int32))

In [ ]:
print(np.empty((20,5), np.int8))

In [ ]:
# random
print(np.random.randint(1, 10, (2,5)))

In [ ]:
print(np.random.rand(3,5))

In [ ]:
print(np.random.randn(3,2))

In [ ]:
# 다차원 배열의 덧셈 

In [ ]:
matrix = np.arange(1, 7).reshape(2, 3)
print(matrix)
print(matrix.sum())

In [ ]:
print(matrix.sum(axis=0))

In [ ]:
print(matrix.sum(axis=1))

In [ ]:
tensor = np.arange(1, 19).reshape(3, 2, 3)
print(tensor)
print(tensor.sum())

In [ ]:
sum(matrix) # 배열 [1,2,3] + [4,5,6] >> [5,6,7]

In [ ]:
[1,2,3] + [4,5,6] 

## 다차원 배열의 합계(sum)

In [ ]:
# 2차원의 합
matrix = np.arange(1, 7).reshape(2, 3)
print(matrix)

In [ ]:
print(matrix.sum(axis=0))
print(matrix.sum(axis=1))

In [ ]:
# 3차원의 합
tensor=np.arange(36).reshape(3,2,6)
print(tensor)

In [ ]:
print(tensor.sum(axis=0))
print()
print(tensor.sum(axis=1))
print()
print(tensor.sum(axis=2))

In [ ]:
print(tensor.mean(axis=2))

In [ ]:
# 4차원의 합
tensor=np.arange(48).reshape(2,2,3,4)
print(tensor)

In [ ]:
print(tensor.sum(axis=0))
print()

In [ ]:
print(tensor.sum(axis=1))
print()

In [ ]:
# 평균(mean)
print(matrix.mean())

In [ ]:
print(matrix.mean(axis=0))
print(matrix.mean(axis=1))

In [ ]:
# 표준편차 (std)
print(matrix.std())
print(matrix.std(axis=0))
print(matrix.std(axis=1))

In [ ]:
# 평균과의 차이를 제곱(**)해서 양수화
# ==> 분산(varianse)  ==> 분산의 제곱근(루트)  ==> 표준편차(std)

In [ ]:
# 분산 var()
print(matrix.var())
print(matrix.var(axis=0))
print(matrix.var(axis=1))

In [ ]:
# 제곱근 sqrt
print(np.sqrt(matrix))

In [ ]:
# 산술연산 -배열끼리의 산술연산/shape이 같아야 가능

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)

In [ ]:
print(np.divide(arr1,arr2))
print(arr1/arr2)

In [ ]:
# Broadcasting : shape가 다른 경우에도 연산 가능, 지원하는 

In [ ]:
scalar = 10
vector = np.array([1, 2, 3])
print(scalar + vector)
scalar == vector

In [ ]:
scalar = 10
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(scalar + matrix)

In [ ]:
matrix = np.arange(1,10).reshape(3, 3)

vector = np.arange(11,14).reshape(3, 1)
print(matrix + vector)

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).reshape(3, 1)
print(arr1)
print(arr2)

In [ ]:
print(arr1+arr2)

In [ ]:

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)

In [ ]:
# 행렬 연산 np.dot(arr1,arr2)
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(arr1 * arr2)

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(arr1 * arr2)

In [ ]:
matrix = np.array([np.random.randint(1, 100) 
for n in range(20)]).reshape(4, 5)
print(matrix)

In [ ]:
np.sort(matrix, axis=1)

In [ ]:
#2차원의 경우 상하 정렬 내림차순
np.sort(matrix, axis=0)[::-1]

In [ ]:
# 2차원 일 경우 좌우 정렬 내림차순

In [ ]:
np.sort(matrix, axis=1)[::-1]

In [ ]:
matrix.max()

In [ ]:
matrix.argmax()

In [ ]:
matrix.max(axis=0)

In [ ]:
matrix.argmax(axis=0)

In [ ]:
c=np.random.randn(2,3)
print(c)

In [ ]:
print(np.argsort(c))

In [ ]:
print(np.argsort(c, axis=0))

In [ ]:
print(np.argsort(c, axis=1))

In [ ]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
print(np.vstack([vector1, vector2]))

In [ ]:
vector1 = np.array([1, 2, 3]).reshape(3, 1)
vector2 = np.array([4, 5, 6]).reshape(3, 1)
print(np.hstack([vector1, vector2]))

In [ ]:
print(np.hstack([vector1, vector2]))

In [ ]:
print(np.vstack([vector1, vector2]))

In [ ]:
print(np.vstack([vector1, vector2]))

In [ ]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
print(np.concatenate([vector1, vector2], axis = 0))

In [ ]:
vector1 = np.array([1, 2, 3]).reshape(3, 1)
print(vector1)
vector2 = np.array([4, 5, 6]).reshape(3, 1)
print(vector2)
print(np.concatenate([vector1, vector2], axis = 1))

In [ ]:
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)
print(np.concatenate([matrix1, matrix2], axis = 0))

In [ ]:
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)
print(np.concatenate([matrix1, matrix2], axis = 1))

In [ ]:
matrix1 = np.arange(1,5).reshape(2,2)
print(matrix1)
print()
matrix2 = np.arange(5,9).reshape(2,2)
print(matrix2)
print()
print(np.vstack([matrix1, matrix2]))

In [108]:
matrix3=np.array([[5,6,7]])
print(matrix3)

[[5 6 7]]


In [109]:
print(matrix3.transpose())
print(matrix3.T)

[[5]
 [6]
 [7]]
[[5]
 [6]
 [7]]
