In [2]:
import numpy as np

In [23]:
#문제 1
# a=np.arange(1,26).reshape(5,5)   #dtype=np.int8 ?
a=np.arange(1,26, dtype=np.int8).reshape(5,5)

In [14]:
np.savetxt('data.csv',a,delimiter=',')

In [21]:
#문제2
arr1=np.loadtxt('data.csv', dtype=str)
arr1

array(['1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00,5.000000000000000000e+00',
       '6.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00,9.000000000000000000e+00,1.000000000000000000e+01',
       '1.100000000000000000e+01,1.200000000000000000e+01,1.300000000000000000e+01,1.400000000000000000e+01,1.500000000000000000e+01',
       '1.600000000000000000e+01,1.700000000000000000e+01,1.800000000000000000e+01,1.900000000000000000e+01,2.000000000000000000e+01',
       '2.100000000000000000e+01,2.200000000000000000e+01,2.300000000000000000e+01,2.400000000000000000e+01,2.500000000000000000e+01'],
      dtype='<U124')

In [40]:
## 지역별 전기요금
data=np.loadtxt('ex1_지역별전기요금.csv',delimiter=',',dtype=int)  # dtype=np.int -error
data[:5,:]

array([[      1,  565082,     273,   27177],
       [      2, 2827233,     444,   45111],
       [      3, 1144913,     289,   29043],
       [      4, 1131034,     230,   22436],
       [      5,  380425,     391,   38020]])

In [28]:
print(data.shape)

(17, 4)


In [34]:
print(np.unique(data[:,0]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [36]:
#전국대상 가구수의 합
print(np.sum(data[:,1]))

14882047


In [39]:
#전력사용량 평균
print(data[:,2].mean())
print(round(data[:,2].mean(),2))

335.1764705882353
335.18


In [43]:
#가구당 평균전력 사용량이 평균이상인 지역과 대상 가구수
a=data[:,2].mean() # 가구당 평균 전력사용량의 전국평균
print(a)
print(data[data[:,2] > a, 0:2])

335.1764705882353
[[      2 2827233]
 [      5  380425]
 [      6  668623]
 [      7  425659]
 [      8  947300]
 [      9 2737725]
 [     10   49394]
 [     11  323151]
 [     12  734723]]


In [53]:
##교통사망사고 데이터
#문제1 상위 3개(발생년도,건수,구성비) 데이터 추출
data=np.loadtxt('ex2_전년대비_시도별_교통사망사고.csv',delimiter=',',dtype=float)  #np.float   -->error
data[:3,[0,2,3]]

array([[2014. ,  218. ,    4.8],
       [2014. ,  872. ,   19. ],
       [2014. ,  401. ,    8.7]])

In [54]:
#세종에서 발생건수
print(data[data[:,1]==10])

[[2.014e+03 1.000e+01 2.000e+01 4.000e-01 0.000e+00 0.000e+00]]
