### Numpy 기초

In [15]:
import numpy as np

In [4]:
array=np.array(1)
array

array(1)

In [7]:
ndarr_1=np.array([1,2,3])
print(type(ndarr_1))

<class 'numpy.ndarray'>


In [8]:
 ndarr_2=np.array([1,2.0,3])
print(ndarr_2)

[1. 2. 3.]


In [9]:
ndarr_3 = np.array ([1, 2.0, '3'])
print(ndarr_3)

['1' '2.0' '3']


In [20]:
ndarr_2=np.dtype
print(ndarr_2)

<class 'numpy.dtype'>


In [21]:
ndarr_1 =np.array ([1, 2,3])
print(ndarr_1)

[1 2 3]


In [22]:
ndarr_2 =np.array ([1, 2.0,3])
print(ndarr_2)

[1. 2. 3.]


In [23]:
ndarr_3 =np.array ([1, 2.0, '3'])
print(ndarr_3)

['1' '2.0' '3']


In [24]:
print(ndarr_1.dtype)
print(ndarr_2.dtype)
print(ndarr_3.dtype)

int32
float64
<U32


In [25]:
print( np.array (1 + 2j).dtype)
print( np.array (print).dtype)

complex128
object


In [26]:
np.str_

numpy.str_

In [28]:
vector =np.array ([1, 2,3])
print(vector)
print( vector.shape)
print( vector.ndim)
print( vector.dtype)
print( vector.size)

[1 2 3]
(3,)
1
int32
3


In [32]:
matrix =np.array ([[1, 2, 3], [4, 5,6]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)
print(matrix.size)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32
6


In [31]:
tensor =np.array ([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11,12]]])
print(tensor)
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)
print(tensor.size)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
int32
12


In [35]:
tensor=np.array([ [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11,12]]],
                   [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11,12]]] ])
print(tensor)
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)
print(tensor.size)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
(2, 2, 2, 3)
4
int32
24


In [ ]:
scalar= = np.srray(1)

In [39]:
matrix=( [[1,2,3],[2,4,6],[3,6,9]] )
np.array(matrix)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [40]:
print(np.array(matrix).size)
print(np.array(matrix).shape)
print(np.array(matrix).ndim)

9
(3, 3)
2


In [45]:
list_ = [[ [ [1, 2], [3, 4] ], [ [5, 6], [7, 8] ] ]]

In [48]:
print(np.array(list_))

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]


In [50]:
arr_ = np.array ([ [ [1, 2], [3, 4] ], [ [5, 6], [7, 8] ] ])

print(arr_[0,0,0])
print(arr_[0,1,1])
print(arr_[1,1,0])

1
4
7


In [55]:
arr_ = np.array([ [ [1, 2], [3, 4] ], [ [5, 6], [7, 8] ] ])
print(arr_)
print(arr_[0,0,0])
print(arr_[0,1,1])
print(arr_[1,1,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
4
7


In [62]:
tensor = np.array([ [ [1, 2, 3],[4, 5, 6]],
                    [ [7, 8, 9],[10, 11, 12] ] ])
print(tensor)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
tensor[[]]

In [ ]:
# 10은 (1,1,0)  2는 (0,0,1)    3은 (0,1,2)  
# 모든 인덱스값을 만들어서 나중에 합쳐서 쓸 것

In [58]:
tensor[[1,0,0],[1,0,1],[0,1,2]]

array([10,  2,  6])

In [65]:
tensor[0, : , 0:2]

array([[1, 2],
       [4, 5]])

In [66]:
tensor[1, : ,2]

array([ 9, 12])